Select * from LesEtudiants;
Select * from LesBatiments;
Select * from LesJardins;
SELECT * FROM LesAppartements;
SELECT * FROM Contient;
SELECT * FROM Garde;
SELECT * FROM Inspecte;
SELECT * FROM Occupe;
SELECT * FROM Partage;